### ISSUE TITLE
安装时报这个错是怎么回事呢

### ISSUE THREAD

**Issue by airenqingqing** [yangweijie/one_admin#2]
安装时报这个错是怎么回事呢?Warning: require(D:\phpstudy_pro\WWW\htshop\vendor\composer/../zoujingli/think-library/src/common.php): failed to open stream: No such file or directory in D:\phpstudy_pro\WWW\htshop\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'D:\phpstudy_pro\WWW\htshop\vendor\composer/../zoujingli/think-library/src/common.php' (include_path='.;C:\php\pear') in D:\phpstudy_pro\WWW\htshop\vendor\composer\autoload_real.php on line 66

**Comment by yangweijie** [comment]
你安装前 composer install 一下试试呢 这个是说composer 找不到 think-library 这个库
